name: Flutter Web Admin CI

on:
  push:
    branches: ["master"]
    paths:
      - 'apps/admin_flutter_web/**'
      - '.github/workflows/flutter-web.yml'
  pull_request:
    branches: ["master"]
    paths:
      - 'apps/admin_flutter_web/**'
      - '.github/workflows/flutter-web.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/admin_flutter_web

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed lib

      - name: Analyze project source
        run: flutter analyze

      - name: Build Web
        run: flutter build web --release
